### ISSUE TITLE
Kino.pub.bat

### ISSUE THREAD

**Issue by nnovofastovskiy** [RockBlack-VPN/ip-address#1]
Загрузил соответствующий bat на роутер но kino.pub не открывается все равно

**Comment by RockBlack-VPN** [comment]
Обновили. [Проверить](https://github.com/RockBlack-VPN/ip-address/blob/main/Global/kino.pub/kino.pub.bat)

**Comment by nnovofastovskiy** [comment]
Все работает, спасибо!
