### ISSUE TITLE
Перестал работать Youtube

### ISSUE THREAD

**Issue by wari0o** [RockBlack-VPN/ip-address#11]
Сегодня перестал работать Youtube. Последнюю версию маршрутов подгрузил, не помогло.
Мб кто-то решил уже проблему?

**Comment by RockBlack-VPN** [comment]
https://github.com/RockBlack-VPN/ip-address/blob/main/Global/Youtube/youtube_m.youtube_insta_meta_torrent_0.0.7.bat
