### ISSUE TITLE
Сделайте пожалуйста .bat файл для Udemy и raycast

### ISSUE THREAD

**Issue by fearintino** [RockBlack-VPN/ip-address#14]
Прошу знатоков сделать .bat файлы с маршрутами для ресурсов Udemy и raycast. Либо пожалуйста дайте инструкцию, как сделать самому. Спасибо!

**Comment by ermakove** [comment]
Udemy - https://github.com/RockBlack-VPN/ip-address/blob/main/Global/udemy/udemy.com.bat

**Comment by fearintino** [comment]
Спасибо большое!
