### ISSUE TITLE
Список адресов OpenAI

### ISSUE THREAD

**Issue by Marblesoul** [RockBlack-VPN/ip-address#15]
С сегодняшнего дня наблюдаю проблемы с доступностью при маршрутизации по текущим ip адресам.
Вероятно следует проверить и актуализировать список.

@RockBlack-VPN

**Comment by RockBlack-VPN** [comment]
update https://github.com/RockBlack-VPN/ip-address/blob/main/Global/ChatGPT(OpenAI)/ChatGPT(OpenAI)_0.0.5.bat
